[package]
name = "actor-framework"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.89"
paste = "1.0.15"
thiserror = "2.0.17"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
